// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_save_restream_config from "./routes/api/save_restream_config.ts";
import * as $api_startTheRelay from "./routes/api/startTheRelay.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $restream from "./routes/restream.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Restream from "./islands/Restream.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
    routes: {
        "./routes/_404.tsx": $_404,
        "./routes/_app.tsx": $_app,
        "./routes/api/joke.ts": $api_joke,
        "./routes/api/save_restream_config.ts": $api_save_restream_config,
        "./routes/api/startTheRelay.ts": $api_startTheRelay,
        "./routes/greet/[name].tsx": $greet_name_,
        "./routes/index.tsx": $index,
        "./routes/restream.tsx": $restream,
    },
    islands: {
        "./islands/Counter.tsx": $Counter,
        "./islands/Restream.tsx": $Restream,
    },
    baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
